# sonar-project.properties
sonar.projectKey=douglas-dreer_pokemon-trade-card-game
sonar.projectName=Pokemon TCG API
sonar.organization=douglas-dreer
sonar.sources=src/main
sonar.tests=src/test
sonar.java.binaries=build/classes
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
sonar.junit.reportPaths=build/test-results/test